### ISSUE TITLE
need capability for account

### ISSUE THREAD

**Issue by benofben** [couchbase-partners/amazon-cloud-formation-couchbase#1]
An error occurred (InsufficientCapabilitiesException) when calling the CreateStack operation: Requires capabilities : [CAPABILITY_IAM]
Bens-MacBook:amazon-cloud-formation-couchbase ben$

**Comment by benofben** [comment]
Opened a helpdesk ticket.  I think this is an issue with my account, not the template.

**Comment by tleyden** [comment]
I believe you just need to add:

```
$ aws cloudformation create-stack ... --capabilities CAPABILITY_IAM 
```

**Comment by benofben** [comment]
Thanks.  Yeah, that works!
