### ISSUE TITLE
Autoscaling Groups - Support Scaling

### ISSUE THREAD

**Issue by benofben** [couchbase-partners/amazon-cloud-formation-couchbase#13]
There's a lot of work here.  It starts to look a bit like a managed service if fully supported.

**Comment by benofben** [comment]
Baby steps.  Let's get parity with Azure first...

**Comment by benofben** [comment]
I wonder if this works automagically in the autoscale group.  Need to test...

**Comment by benofben** [comment]
It works!  Need to record a video...

**Comment by benofben** [comment]
Spoke too soon... It doesn't always rally on the same node, so sometime you end up with two clusters --- the pre scale cluster and a second cluster based on the new rally point post scale.  Need to enforce rallying on a prexisting node.

**Comment by benofben** [comment]
Yuck.  This is really complicated because we can't figure out how to number the machines.  Karthik is checking to see if there's anything else as an option.  The recommended solution apparently involves Lambda and S3 or DynamoDB.

**Comment by tleyden** [comment]
If you end up doing anything with lamba + dynamo, I can walk you through what I did in cbbootstrap in case you want to cherry pick anything 

https://github.com/couchbase/cbbootstrap

**Comment by benofben** [comment]
That's an interesting solution, though I'd like to avoid the lambda+dynamodb dependency.  I think we're close.  I'm tempted to depend on the tags to manage it, though that seems a little problematic..

**Comment by benofben** [comment]
I'm wondering if removing the sort on the metadata call would fix things.  If the metadata service has a natural order, that'd work.   Going to test that...

I really just need to find something with a natural order that doesn't change on scaling.  That's why the current solution doesn't work.  An alternative would be to detect a scaling operation versus a new spinup and then as for the node with the ServerRally tag, but that's a much more brittle solution.

**Comment by benofben** [comment]
I think I might know how to do this by chaining the rally rather than making it a single point.  Need to think it through a bit more....

**Comment by benofben** [comment]
So, I think my previous suggestion was effective a perpetual motion machine.

However ---- I think by adding a loop where nodes to to connect to every node on start and then fall back to the designated rally when that fails will work.

**Comment by benofben** [comment]
oooh.  New approach --- loop through the instances and check if one has the rally tag set.  If so, we rally on it.  If not, we continue as normal.

**Comment by benofben** [comment]
or maybe a function called "attempt to rally on existing node"  still concerned about coupling to the tag thing plus there are complexities grabbing all groups within a stack.

**Comment by benofben** [comment]
hmmm.  but if we go to the MDS model where there are groups without some type of node that won't work.  Maybe tag within stack is the best way?

**Comment by benofben** [comment]
Ok.  That worked scaling simple from 2 nodes to 10.  Going to check it on granular now, but I think we're good.  Here's the commit that did it...
https://github.com/couchbase-partners/amazon-cloud-formation-couchbase/commit/b5aaa90f39cd9c76dc6f357d7786913f299998d9

**Comment by benofben** [comment]
Didn't work for granular...  need to dig into that.

**Comment by benofben** [comment]
Ok.  This seems to be fixed for the generator now too.  I requested a quota increase so I can try it with 50 nodes, but I'm calling it done for now.

**Comment by benofben** [comment]
I think I came up with a more elegant solution for this last night.   On each node:

check if rally tag for stack is set.
if not, attempt to set it
wait 1 second for any parallel writes
read it

I believe this works so long as any write to a tag completes in less than 1 second.

**Comment by benofben** [comment]
Could also add some code here to check if the rally is still live and replace it if not.
